<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_cName</name>
   <tag></tag>
   <elementGuidId>8e5e931b-11d8-4cb1-9a01-e15961e9d227</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#main-big-col > form > input:nth-child(11)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[count(. | //*[@class = 'nor']) = count(//*[@class = 'nor'])][count(. | //*[@type = 'text']) = count(//*[@type = 'text'])][count(. | //*[@name = 'cName']) = count(//*[@name = 'cName'])][count(. | //*[@value = 'Ivan']) = count(//*[@value = 'Ivan'])][count(. | //*[@size = '40']) = count(//*[@size = '40'])][count(. | //*[@maxlength = '255']) = count(//*[@maxlength = '255'])][count(. | id(&quot;main-big-col&quot;)/form[1]/input[@class=&quot;nor&quot;]) = count(id(&quot;main-big-col&quot;)/form[1]/input[@class=&quot;nor&quot;])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nor</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cName</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Ivan</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>40</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-big-col&quot;)/form[1]/input[@class=&quot;nor&quot;]</value>
   </webElementProperties>
</WebElementEntity>
