<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Sencanska</name>
   <tag></tag>
   <elementGuidId>2c1a745b-12ff-40d4-9f18-5dc4b882576c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#main-big-col > form > textarea</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//textarea[count(. | //*[@class = 'nor']) = count(//*[@class = 'nor'])][count(. | //*[@rows = '5']) = count(//*[@rows = '5'])][count(. | //*[@cols = '40']) = count(//*[@cols = '40'])][count(. | //*[@name = 'cAddress']) = count(//*[@name = 'cAddress'])][count(. | //*[text() = 'Sencanska']) = count(//*[text() = 'Sencanska'])][count(. | id(&quot;main-big-col&quot;)/form[1]/textarea[@class=&quot;nor&quot;]) = count(id(&quot;main-big-col&quot;)/form[1]/textarea[@class=&quot;nor&quot;])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nor</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>40</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cAddress</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sencanska</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-big-col&quot;)/form[1]/textarea[@class=&quot;nor&quot;]</value>
   </webElementProperties>
</WebElementEntity>
