<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Books</name>
   <tag></tag>
   <elementGuidId>e1e69631-d7ab-4609-94cd-56f2262e2895</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;main-menu&quot;]/a[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[count(. | //*[@href = 'index.php?page=books']) = count(//*[@href = 'index.php?page=books'])][count(. | //*[text() = 'Books']) = count(//*[text() = 'Books'])][count(. | id(&quot;main-big-col&quot;)/div[@id=&quot;product-list&quot;]/div[@class=&quot;item&quot;]/b[1]/a[1]) = count(id(&quot;main-big-col&quot;)/div[@id=&quot;product-list&quot;]/div[@class=&quot;item&quot;]/b[1]/a[1])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>index.php?page=books</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Books</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-big-col&quot;)/div[@id=&quot;product-list&quot;]/div[@class=&quot;item&quot;]/b[1]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
