<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ses_login</name>
   <tag></tag>
   <elementGuidId>df773ae4-bc33-403b-8e4c-395a1eaf9178</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[count(. | //*[@class = 'formbtn']) = count(//*[@class = 'formbtn'])][count(. | //*[@type = 'submit']) = count(//*[@type = 'submit'])][count(. | //*[@name = 'ses_login']) = count(//*[@name = 'ses_login'])][count(. | //*[@value = 'Login']) = count(//*[@value = 'Login'])][count(. | id(&quot;main-big-col&quot;)/form[1]/input[@class=&quot;formbtn&quot;]) = count(id(&quot;main-big-col&quot;)/form[1]/input[@class=&quot;formbtn&quot;])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formbtn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ses_login</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Login</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-big-col&quot;)/form[1]/input[@class=&quot;formbtn&quot;]</value>
   </webElementProperties>
</WebElementEntity>
