<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Biographies</name>
   <tag></tag>
   <elementGuidId>18bed24d-8267-4ebd-8975-db3b0035a39c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#product-list > div:nth-child(5) > a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[count(. | //*[@class = 'cat-box']) = count(//*[@class = 'cat-box'])][count(. | //*[@href = 'index.php?page=books&amp;category=books-biographies']) = count(//*[@href = 'index.php?page=books&amp;category=books-biographies'])][count(. | //*[text() = 'Biographies']) = count(//*[text() = 'Biographies'])][count(. | id(&quot;product-list&quot;)/div[@class=&quot;cat-wrapper&quot;]/a[@class=&quot;cat-box&quot;]) = count(id(&quot;product-list&quot;)/div[@class=&quot;cat-wrapper&quot;]/a[@class=&quot;cat-box&quot;])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cat-box</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>index.php?page=books&amp;category=books-biographies</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Biographies</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-list&quot;)/div[@class=&quot;cat-wrapper&quot;]/a[@class=&quot;cat-box&quot;]</value>
   </webElementProperties>
</WebElementEntity>
